In [1]:
import pandas as pd   # module to work with data in DataFrames.
import seaborn as sns  # module to plot DataFrames in an easy way
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats

In [2]:
sns.set_context('poster') # other optionss are: 'poster', 'notebook'

## 0. Daten Einlesen

In [3]:
# read orignal data
odf = pd.read_csv('data.csv', encoding = "ISO-8859-1")

# read info data
idf = pd.read_csv('dataset\data-infos.csv', encoding = "ISO-8859-1", sep = ';')

In [4]:
# explore orignal data
odf

CASE                           SERIAL  \
0   Interview-Nummer (fortlaufend)  Seriennummer (sofern verwendet)   
1                               59                              NaN   
2                               68                              NaN   
3                               70                              NaN   
4                               75                              NaN   
5                               76                              NaN   
6                               78                              NaN   
7                               80                              NaN   
8                               86                              NaN   
9                               89                              NaN   
10                              95                              NaN   
11                              96                              NaN   
12                              97                              NaN   
13                              98                              NaN   
14                             100                              NaN   

                                    REF  \
0   Referenz (sofern im Link angegeben)   
1                                   NaN   
2                                   NaN   
3                                   NaN   
4                                   NaN   
5                                   NaN   
6                                   NaN   
7                                   NaN   
8                                   NaN   
9                                   NaN   
10                                  NaN   
11                                  NaN   
12                                  NaN   
13                                  NaN   
14                                  NaN   

                                        QUESTNNR             MODE  \
0   Fragebogen, der im Interview verwendet wurde  Interview-Modus   
1                                          final        interview   
2                                          final        interview   
3                                          final        interview   
4                                          final        interview   
5                                          final        interview   
6                                          final        interview   
7                                          final        interview   
8                                          final        interview   
9                                          final        interview   
10                                         final        interview   
11                                         final        interview   
12                                         final        interview   
13                                         final        interview   
14                                         final        interview   

                                              STARTED           B001_01  \
0   Zeitpunkt zu dem das Interview begonnen hat (E...  0-Frage: 0-0.jpg   
1                                 2022-06-23 11:50:35                 1   
2                                 2022-06-28 14:03:06                 4   
3                                 2022-07-04 14:07:53                 3   
4                                 2022-07-04 16:26:49                 4   
5                                 2022-07-04 16:34:24                 4   
6                                 2022-07-04 17:00:34                 2   
7                                 2022-07-04 17:44:38                 1   
8                                 2022-07-04 18:10:28                 4   
9                                 2022-07-04 19:05:20                 4   
10                                2022-07-04 21:46:43                 4   
11                                2022-07-04 21:57:59                 5   
12                                2022-07-05 00:08:11                 5   
13                                2022-07-05 00:5

In [5]:
# explore info data
idf

Picture Series  Picture   Price Gallery  Category  \
0                   0        0  0.2000     KPR         1   
1                   0        1  0.1700     KPR         1   
2                   0        2  0.1499     KPR         1   
3                   0        3  0.1290     KPR         1   
4                   0        4  0.1200     KPR         1   
..                ...      ...     ...     ...       ...   
95                 19        0  0.8800     WMN         2   
96                 19        1  0.8800     WMN         2   
97                 19        2  0.8800     WMN         2   
98                 19        3  0.8800     WMN         2   
99                 19        4  0.8800     WMN         2   

                                                 Link  
0   https://opensea.io/assets/ethereum/0xcb1021080...  
1   https://opensea.io/assets/ethereum/0xcb1021080...  
2   https://opensea.io/assets/ethereum/0xcb1021080...  
3   https://opensea.io/assets/ethereum/0xcb1021080...  
4   https://opensea.io/assets/ethereum/0xcb1021080...  
..                                                ...  
95  https://opensea.io/assets/ethereum/0xbee7cb80d...  
96  https://opensea.io/assets/ethereum/0xbee7cb80d...  
97  https://opensea.io/assets/ethereum/0xbee7cb80d...  
98  https://opensea.io/assets/ethereum/0xbee7cb80d...  
99  https://opensea.io/assets/ethereum/0xbee7cb80d...  

[100 rows x 6 columns]

In [6]:
#select needed rows
odf=odf.loc[1:,"B001_01":"B020_05"]

# explore orignal data
odf

B001_01 B001_02 B001_03 B001_04 B001_05 B002_01 B002_02 B002_03 B002_04  \
1        1       4       2       3       5       4       2       3       1   
2        4       1       5       3       2       3       1       2       4   
3        3       4       5       1       2       2       4       1       5   
4        4       3       5       1       2       5       1       2       3   
5        4       1       5       2       3       2       5       1       4   
6        2       1       5       3       4       4       5       2       1   
7        1       3       5       2       4       4       3       2       1   
8        4       1       3       5       2       1       2       3       4   
9        4       3       5       2       1       4       1       5       3   
10       4       2       5       1       3       5       1       2       4   
11       5       1       3       4       2       5       3       1       2   
12       5       3       1       4       2       1       3       2       5   
13       3       1       5       4       2       1       5       2       3   
14       5       3       4       2       1       3       2       1       4   

   B002_05  ... B019_01 B019_02 B019_03 B019_04 B019_05 B020_01 B020_02  \
1        5  ...       3       2       4       1       5       4       2   
2        5  ...       1       5       3       2       4       1       4   
3        3  ...       3       5       1       2       4       3       4   
4        4  ...       2       5       4       1       3       1       2   
5        3  ...       2       1       5       4       3       5       4   
6        3  ...       2       1       4       5       3       5       1   
7        5  ...       2       4       5       1       3       5       3   
8        5  ...       4       2       1       5       3       3       2   
9        2  ...       3       1       5       4       2       5       2   
10       3  ...       5       4       3       1       2       1       5   
11       4  ...       2       4       1       5       3       3       1   
12       4  ...       5       3       2       1       4       1       2   
13       4  ...       1       4       2       5       3       2       5   
14       5  ...       2       4       1       5       3       2       5   

   B020_03 B020_04 B020_05  
1        5       3       1  
2        3       5       2  
3        5       2       1  
4        3       5       4  
5        3       1       2  
6        3       4       2  
7        4       1       2  
8        4       1       5  
9        1       3       4  
10       4       2       3  
11       4       2       5  
12       4       5       3  
13       4       1       3  
14       4       3       1  

[14 rows x 100 columns]

In [7]:
number_of_cases = len(odf)

In [8]:
#function to transform df
def transform(odf):
    #get data head
    head = list(odf.columns.values)

    #create new d
    df = pd.DataFrame(columns=['Case','Picture Series','Picture','Price','Gallery','Category','Rank'])
    
    #iterate through every row
    for i in range(len(odf)):
        
        #iterate through every column
        for j in range(len(head)):
            
            column_head = head[j] # column name: 'B0XX_0Y'
            
            # create new row
            cas = i #'Case': every row of odf is one case
            
            pcs = int(column_head[2] + column_head[3]) - 1 #'Picture Series': get XX from 'B0XX_0Y'
            pct = int(column_head[6]) - 1 #'Picture': get Y from 'B0XX_0Y'
            
            prc = idf.iloc[j, 2] #'Price': get price from idf
            gll = idf.iloc[j, 3] #'Gallery': get gallery from idf
            ctg = idf.iloc[j, 4] #'Category': get category from idf
            
            rnk = odf.iloc[i, j] #'Rank': get rank from odf
            
            df2 = pd.DataFrame({'Case': [cas],
                    'Picture Series' : [pcs],
                    'Picture' : [pct],
                    'Price' : [prc],
                    'Gallery' : [gll],
                    'Category' : [ctg],            
                    'Rank' : [rnk]})
            
            df = pd.concat([df, df2], ignore_index = True, axis = 0)
            
    return df

In [9]:
#create new df
df = transform(odf)

# explor new transformed data
pd.set_option('display.max_rows', None)
df

Case Picture Series Picture   Price Gallery Category Rank
0       0              0       0     0.2     KPR        1    1
1       0              0       1    0.17     KPR        1    4
2       0              0       2  0.1499     KPR        1    2
3       0              0       3   0.129     KPR        1    3
4       0              0       4    0.12     KPR        1    5
5       0              1       0     3.1     WMN        1    4
6       0              1       1    1.99     WMN        1    2
7       0              1       2   1.111     WMN        1    3
8       0              1       3     0.9     WMN        1    1
9       0              1       4    0.75     WMN        1    5
10      0              2       0     1.0     BST        1    5
11      0              2       1     0.5     BST        1    3
12      0              2       2    0.38     BST        1    2
13      0              2       3     0.2     BST        1    1
14      0              2       4    0.78     BST        1    4
15      0              3       0    75.0     WHR        1    2
16      0              3       1    55.0     WHR        1    3
17      0              3       2    45.0     WHR        1    5
18      0              3       3   28.75     WHR        1    4
19      0              3       4    15.0     WHR        1    1
20      0              4       0     1.2     THM        1    5
21      0              4       1     1.0     THM        1    1
22      0              4       2    0.75     THM        1    4
23      0              4       3     0.5     THM        1    3
24      0              4       4  0.4207     THM        1    2
25      0              5       0     2.0     GRN        1    3
26      0              5       1     1.2     GRN        1    5
27      0              5       2    0.99     GRN        1    1
28      0              5       3    0.69     GRN        1    2
29      0              5       4    0.25     GRN        1    4
30      0              6       0     1.0     BST        1    1
31      0              6       1     0.8     BST        1    4
32      0              6       2    0.68     BST        1    5
33      0              6       3     0.5     BST        1    2
34      0              6       4   0.349     BST        1    3
35      0              7       0     2.5     WMN        1    5
36      0              7       1     2.2     WMN        1    2
37      0              7       2    1.65     WMN        1    3
38      0              7       3    1.25     WMN        1    4
39      0              7       4    0.98     WMN        1    1
40      0              8       0   130.0     JST        1    1
41      0              8       1   100.0     JST        1    2
42      0              8       2    69.0     JST        1    4
43      0              8       3    49.0     JST        1    5
44      0              8       4    30.0     JST        1    3
45      0              9       0   100.0     JST        1    3
46      0              9       1   85.69     JST        1    5
47      0              9       2    55.0     JST        1    4
48      0              9       3  40.666     JST        1    1
49      0              9       4     4.5     JST        1    2
50      0             10       0    1.38     PLT        1    5
51      0             10       1     0.5     PLT        1    2
52      0             10       2    0.39     PLT        1    1
53      0             10       3    0.32     PLT        1    3
54      0             10       4     0.3     PLT        1    4
55      0             11       0    0.37     CLR        1    3
56      0             11       1   0.295     CLR        1    2
57      0             11       2    0.25     CLR        1    4
58      0             11       3    0.15     CLR        1    5
59      0             11       4    0.12     CLR        1    1
60      0             12       0    0.48     THM        1    1
61      0             12       1   0.419     THM        1    4
62      0             12       2   0

In [10]:
#pd.set_option('display.max_rows', 10)

## 1. Daten auf Konsistenz prüfen

In [11]:
# if there were 9 different observers
observers = 9
counted_cases = len(df['Case'].unique())
print(df['Case'].unique())
print (counted_cases)

# 20 series
counted_series = len(df['Picture Series'].unique())
print(df['Picture Series'].unique())
print (counted_series)

# 5 pictures per series
counted_pics = len(df['Picture'].unique())
print(df['Picture'].unique())
print (counted_pics)

# 5 different given ranks
counted_ranks = len(df['Rank'].unique())
print(df['Rank'].unique())
print (counted_ranks)

# 5 different original ranks
#counted_original_ranks = len(df[''].unique())
#print(df[''].unique())
#print (counted_original_ranks)

# 13 galleries
counted_galleries = len(df['Gallery'].unique())
print(df['Gallery'].unique())
print (counted_galleries)

[0 1 2 3 4 5 6 7 8 9 10 11 12 13]
14
[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19]
20
[0 1 2 3 4]
5
['1' '4' '2' '3' '5']
5
['KPR' 'WMN' 'BST' 'WHR' 'THM' 'GRN' 'JST' 'PLT' 'CLR' 'BTF' 'TYL' 'DSR'
 'SPR']
13


In [12]:
# match expected rows?
rows = len(df)
print(rows)
total_rows = counted_cases * counted_series * counted_pics
print(total_rows)

1400
1400


## 2. Deskriptive Datenanalyse

## 3. Statistische Analyse

### pearson correlation

#### correlation for each picture series --> fischer z transformation --> mean of Z --> transformation to correlation

In [21]:
#convert ranks from String to int
df['Rank'] = df['Rank'].astype('int')
#calculate sums
df_sum = df.groupby(['Picture Series','Picture'],as_index=False).agg({'Rank': 'sum'})

# convert to np array
data = np.zeros((100, 2))

for i in range(100):
    #price
    data[i][0] = float(idf.iloc[i, 2])
    #rank
    data[i][1] = df_sum.iloc[i,2]

    
# calculate pearson correlation for each picture series
r = np.zeros((20))
for i in range(20):
    pos = i*5
    data_ps = data[pos:pos+5]
    
    x = data_ps[:,0]
    y = data_ps[:, 1]
    
    if np.amax(x)-np.amin(x) != 0:
        r[i] = np.corrcoef(x,y)[0][1]
    else:
        r[i] = 0

# fischer z transformation
Z = np.zeros((20))
for i in range(20):
    
    Z[i] = 0.5 * np.log((1+r[i]) / (1-r[i]))

# get mean 
Z_ = np.mean(Z)

# transfrom back to corr
r_ = (np.exp(2 * Z_) - 1) / (np.exp(2 * Z_) + 1)

r_

0.18113838092217782

In [22]:
r

array([ 0.30708963, -0.12464905,  0.8291888 ,  0.43983143,  0.21262469,
        0.44651579, -0.14132866,  0.38226778, -0.65289443,  0.81578229,
        0.71065651, -0.61754023, -0.00716067, -0.1919283 , -0.25484561,
       -0.53071401,  0.        ,  0.88070485,  0.        ,  0.        ])

### spearman correlation

### pearson for each category

#### categroy 1

In [16]:
#convert ranks from String to int
df['Rank'] = df['Rank'].astype('int')
#calculate sums
df_sum = df.groupby(['Picture Series','Picture'],as_index=False).agg({'Rank': 'sum'})

# convert to np array
data = np.zeros((75, 2))

for i in range(75):
    #price
    data[i][0] = float(idf.iloc[i, 2])
    #rank
    data[i][1] = df_sum.iloc[i,2]

    
# calculate pearson correlation for each picture series
r = np.zeros((15))
for i in range(15):
    pos = i*5
    data_ps = data[pos:pos+5]
    
    x = data_ps[:,0]
    y = data_ps[:, 1]
    
    if np.amax(x)-np.amin(x) != 0:
        r[i] = np.corrcoef(x,y)[0][1]
    else:
        r[i] = 0

# fischer z transformation
Z = np.zeros((15))
for i in range(15):
    
    Z[i] = 0.5 * np.log((1+r[i]) / (1-r[i]))

# get mean 
Z_ = np.mean(Z)

# transfrom back to corr
r_ = (np.exp(2 * Z_) - 1) / (np.exp(2 * Z_) + 1)

r_

0.1893810506356581

In [18]:
# is r_ statistically significant
# alpha value
alpha = 0.1
# t value
df_ = number_of_cases - 2
t_df = (r_ * np.sqrt(df_)) / (np.sqrt(1 - r_**2))

t_crit = scipy.stats.t.ppf(q=1-alpha/2,df = df_)

# if true then r_ is not significant
print(t_df <= t_crit)
print(t_df)
print(t_crit)

True
0.6681258286906412
1.782287555649159


#### categroy 2

In [19]:
#convert ranks from String to int
df['Rank'] = df['Rank'].astype('int')
#calculate sums
df_sum = df.groupby(['Picture Series','Picture'],as_index=False).agg({'Rank': 'sum'})

# convert to np array
data = np.zeros((25, 2))

for i in range(25):
    #price
    data[i][0] = float(idf.iloc[75 + i, 2])
    #rank
    data[i][1] = df_sum.iloc[75 + i,2]

    
# calculate pearson correlation for each picture series
r = np.zeros((5))
for i in range(5):
    pos = i*5
    data_ps = data[pos:pos+5]
    
    x = data_ps[:,0]
    y = data_ps[:, 1]
    
    if np.amax(x)-np.amin(x) != 0:
        r[i] = np.corrcoef(x,y)[0][1]
    else:
        r[i] = 0

# fischer z transformation
Z = np.zeros((5))
for i in range(5):
    
    Z[i] = 0.5 * np.log((1+r[i]) / (1-r[i]))

# get mean 
Z_ = np.mean(Z)

# transfrom back to corr
r_ = (np.exp(2 * Z_) - 1) / (np.exp(2 * Z_) + 1)

r_

0.15626158651213864

In [20]:
# is r_ statistically significant
# alpha value
alpha = 0.1
# t value
df_ = number_of_cases - 2
t_df = (r_ * np.sqrt(df_)) / (np.sqrt(1 - r_**2))

t_crit = scipy.stats.t.ppf(q=1-alpha/2,df = df_)

# if true then r_ is not significant
print(t_df <= t_crit)
print(t_df)
print(t_crit)

True
0.5480382773482353
1.782287555649159
